// src/config/roles.js
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  CIU_ANALYST: "CIU_ANALYST",
  CIU_SUPERVISOR: "CIU_SUPERVISOR",
  INVESTIGATION_OFFICER: "INVESTIGATION_OFFICER",
  CYBER_OFFICER: "CYBER_OFFICER",
  RISK_OFFICER: "RISK_OFFICER",
  AUDITOR: "AUDITOR",
};